name: 🐈 Deploy to neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 🖥️Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        if: ${{ env.NEOCITIES_API_TOKEN }} # BUG: REMOVE
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public